/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
/// <reference types="nativewind/types" />
import { ImageSourcePropType } from 'react-native';

declare module '*.png' {
  const content: ImageSourcePropType;
  export default content;
}
